In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
a[0]

1

In [9]:
b[0,0]

1

In [10]:
c[0,1,1]

4

In [11]:
a[2]

3

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b[1,0]

4

In [9]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
c[1,0,1]

6

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
a[-1]

5

In [17]:
b


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b[-1]

array([4, 5, 6])

In [19]:
b[-1,-1]

6

In [20]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
c[-1]

array([[5, 6],
       [7, 8]])

In [22]:
c[-1,-1]

array([7, 8])

In [23]:
c[-1,-1,-1]

8

## [:], [::], ...Acceder a varios elementos de un array.



In [12]:
r = np.arange(60).reshape(5,3,4)

In [6]:
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [26]:
r[1:3]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [32]:
r[1:-2]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [27]:
r[0:5:2]#de la 0 a la 4 de 2 en 2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [28]:
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [29]:
r[2:3]

array([[[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [30]:
r[2:3,1:2]

array([[[29, 30]]])

In [7]:
r[2,1]

array([28, 29, 30, 31])

In [39]:
r[-1,-1,1:3]
r[4:5,2:3,1:3]

array([[[57, 58]]])

In [10]:
r[:,1:2,0:2]

array([[[ 4,  5]],

       [[16, 17]],

       [[28, 29]],

       [[40, 41]],

       [[52, 53]]])

In [31]:
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [89]:
r[0:3]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [90]:
r[0:3,2:3]

array([[[ 8,  9, 10, 11]],

       [[20, 21, 22, 23]],

       [[32, 33, 34, 35]]])

In [91]:
r[0:3,2:3,1:3]

array([[[ 9, 10]],

       [[21, 22]],

       [[33, 34]]])

In [93]:
r[0:1,2:3,1:3]

array([[[ 9, 10]]])

In [32]:
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [33]:
r[:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [97]:
r[:,:,1:]

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]],

       [[25, 26, 27],
        [29, 30, 31],
        [33, 34, 35]],

       [[37, 38, 39],
        [41, 42, 43],
        [45, 46, 47]],

       [[49, 50, 51],
        [53, 54, 55],
        [57, 58, 59]]])

In [ ]:
r[1:2,0:,2:3]


array([[[14],
        [18],
        [22]]])

In [13]:
r


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])