In [3]:
import cv2
import numpy as np

In [ ]:
#open cv

# pip install opencv-python


In [4]:
imagen = cv2.imread('R.jpg')


In [12]:
imagen_np = np.array(imagen)
print(imagen_np.shape)
print(imagen)

(570, 800, 3)
[[[133 231 131]
  [133 231 131]
  [133 231 131]
  ...
  [127 219 122]
  [127 219 122]
  [127 219 122]]

 [[133 231 131]
  [133 231 131]
  [133 231 131]
  ...
  [127 219 122]
  [127 219 122]
  [127 219 122]]

 [[133 231 131]
  [133 231 131]
  [133 231 131]
  ...
  [127 219 122]
  [127 219 122]
  [127 219 122]]

 ...

 [[123 221 119]
  [123 221 119]
  [123 221 119]
  ...
  [100 196  96]
  [100 196  96]
  [100 196  96]]

 [[123 221 119]
  [123 221 119]
  [123 221 119]
  ...
  [ 99 195  93]
  [ 99 195  93]
  [ 99 195  93]]

 [[123 221 119]
  [123 221 119]
  [123 221 119]
  ...
  [ 99 195  93]
  [ 99 195  93]
  [ 99 195  93]]]


In [13]:
# Convertir la imagen al espacio de color HSV (Hue, Saturation, Value)
hsv = cv2.cvtColor(imagen, cv2.COLOR_BGR2HSV)

In [14]:
bajo_verde = np.array([35, 40, 40])
alto_verde = np.array([85, 255, 255])

In [15]:
# Crear una máscara con los píxeles que están dentro del rango del color verde
mascara = cv2.inRange(hsv, bajo_verde, alto_verde)


In [16]:
# Invertir la máscara para obtener la imagen sin el fondo verde
mascara_invertida = cv2.bitwise_not(mascara)

In [17]:
# Aplicar la máscara invertida para quitar el fondo verde de la imagen original
resultado = cv2.bitwise_and(imagen, imagen, mask=mascara_invertida)

In [18]:
# Mostrar la imagen original y el resultado sin el fondo verde
cv2.imshow('Imagen Original', imagen)
cv2.imshow('Imagen sin Fondo Verde', resultado)

In [19]:
# Guardar la imagen sin el fondo verde
cv2.imwrite('imagen_sin_fondo.jpg', resultado)

True